/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void custom_slider1_change1(GCustomSlider source, GEvent event) { //_CODE_:custom_slider1:406579:
  println("custom_slider1 - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:custom_slider1:406579:

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:Clock:788938:
  appc.background(230);
} //_CODE_:Clock:788938:

public void timer1_Action1(GTimer source) { //_CODE_:timer1:527622:
  println("timer1 - GTimer >> an event occured @ " + millis());
} //_CODE_:timer1:527622:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  custom_slider1 = new GCustomSlider(this, 170, 153, 100, 40, "grey_blue");
  custom_slider1.setLimits(0.5, 0.0, 1.0);
  custom_slider1.setNumberFormat(G4P.DECIMAL, 2);
  custom_slider1.setOpaque(false);
  custom_slider1.addEventHandler(this, "custom_slider1_change1");
  Clock = GWindow.getWindow(this, "Window title", 0, 0, 400, 300, JAVA2D);
  Clock.noLoop();
  Clock.setActionOnClose(G4P.KEEP_OPEN);
  Clock.addDrawHandler(this, "win_draw1");
  timer1 = new GTimer(this, this, "timer1_Action1", 1000);
  Clock.loop();
}

// Variable declarations 
// autogenerated do not edit
GCustomSlider custom_slider1; 
GWindow Clock;
GTimer timer1; 
